### Listar vendas
POST https://localhost:5001/api/formapagamento/create
Content-Type: application/json

{
 "Tipo": "Cartao",
 "Descricao": "Cartao de credito"
}

#  "Tipo": "pIX",
#  "Descricao": "pix feliz"

###listar
GET https://localhost:5001/api/formapagamento/list


### Deletar um produto pelo nome
DELETE https://localhost:5001/api/formapagamento/delete/Cartao
